"""add detailed client information

Revision ID: 02d594cf35ae
Revises: 9a7a485fed82
Create Date: 2025-08-21 14:48:32.678545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d594cf35ae'
down_revision = '9a7a485fed82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('entity_structure', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('services_offered', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('billing_cycle', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('client_status', sa.String(length=20), nullable=True, server_default='Active'))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # Copy data from old 'name' column to new columns
    op.execute('UPDATE client SET contact_name = name, business_name = name')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('contact_name', nullable=False)
        batch_op.alter_column('business_name', nullable=False)
        batch_op.create_unique_constraint('uq_client_business_name', ['business_name'])
        batch_op.drop_column('name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=True))

    op.execute('UPDATE client SET name = contact_name')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('name', nullable=False)
        batch_op.drop_constraint('uq_client_business_name', type_='unique')
        batch_op.drop_column('notes')
        batch_op.drop_column('client_status')
        batch_op.drop_column('billing_cycle')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('services_offered')
        batch_op.drop_column('entity_structure')
        batch_op.drop_column('address')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('business_name')
        batch_op.drop_column('contact_name')
    # ### end Alembic commands ###
