"""add locked field to journal entry

Revision ID: 04f32eee6b09
Revises: ab5ef2d7920a
Create Date: 2025-08-17 17:12:45.283731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f32eee6b09'
down_revision = 'ab5ef2d7920a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('locked')

    # ### end Alembic commands ###
