"""Add purpose to PendingPlaidLink

Revision ID: 058b84186064
Revises: 308be7a44f30
Create Date: 2025-10-07 11:05:17.543261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058b84186064'
down_revision = '308be7a44f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = inspector.get_columns('pending_plaid_link')
    column_names = [col['name'] for col in columns]

    if 'purpose' not in column_names:
        with op.batch_alter_table('pending_plaid_link', schema=None) as batch_op:
            batch_op.add_column(sa.Column('purpose', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = inspector.get_columns('pending_plaid_link')
    column_names = [col['name'] for col in columns]

    if 'purpose' in column_names:
        with op.batch_alter_table('pending_plaid_link', schema=None) as batch_op:
            batch_op.drop_column('purpose')
    # ### end Alembic commands ###
