"""Add status to JournalEntry

Revision ID: 086cfae372b1
Revises: 83e9a18bce4d
Create Date: 2025-08-24 12:17:14.056341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086cfae372b1'
down_revision = '83e9a18bce4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='posted'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
