"""Add debit and credit account to Transaction model

Revision ID: 0ae6d8e0947a
Revises: df147c069a8a
Create Date: 2025-08-24 19:45:10.679175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae6d8e0947a'
down_revision = 'df147c069a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debit_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credit_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_debit_account_id', 'account', ['debit_account_id'], ['id'])
        batch_op.create_foreign_key('fk_transaction_credit_account_id', 'account', ['credit_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_debit_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_transaction_credit_account_id', type_='foreignkey')
        batch_op.drop_column('credit_account_id')
        batch_op.drop_column('debit_account_id')

    # ### end Alembic commands ###
