"""Add client_id to ImportTemplate

Revision ID: 0f2c1801113a
Revises: 8ee0cfd10a49
Create Date: 2025-08-30 21:19:48.872736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2c1801113a'
down_revision = '8ee0cfd10a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    # Get the first client
    first_client = session.execute(sa.text("SELECT id FROM client ORDER BY id LIMIT 1")).scalar_one_or_none()

    # If there are no clients, we can't set a default, but this shouldn't happen in a populated DB
    if first_client is None:
        first_client = 1 # Fallback for empty DB, though this is not ideal

    with op.batch_alter_table('import_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False, server_default=str(first_client)))
        batch_op.create_foreign_key('fk_import_template_client_id', 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_template', schema=None) as batch_op:
        batch_op.drop_constraint('fk_import_template_client_id', type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
