"""create rule_account_link table

Revision ID: 0f71d38505d8
Revises: e768a541bded
Create Date: 2025-08-15 22:39:09.004175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f71d38505d8'
down_revision = 'e768a541bded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_account_link',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('is_exclusion', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.PrimaryKeyConstraint('rule_id', 'account_id')
    )
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rule_account_id'), type_='foreignkey')
        batch_op.drop_column('is_exclusion')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_exclusion', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_rule_account_id'), 'account', ['account_id'], ['id'])

    op.drop_table('rule_account_link')
    # ### end Alembic commands ###
