"""add keywords to budget model

Revision ID: 1392468a00d6
Revises: b9be6e2c60ce
Create Date: 2025-11-04 15:56:07.651267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1392468a00d6'
down_revision = 'b9be6e2c60ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('budget_keywords',
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('budget_id', 'keyword_id')
    )
    # with op.batch_alter_table('audit_trail', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('audit_trail', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'client', ['user_id'], ['id'])

    op.drop_table('budget_keywords')
    op.drop_table('keyword')
    # ### end Alembic commands ###
