"""add reversing entry fields

Revision ID: 1a95bf4917c9
Revises: 675be0e1338f
Create Date: 2025-08-24 11:52:16.741636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a95bf4917c9'
down_revision = '675be0e1338f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reversing', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('reversal_date', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('reversal_date')
        batch_op.drop_column('is_reversing')

    # ### end Alembic commands ###
