"""Add manual assignment flag to transaction rules and transactions

Revision ID: 2197cb1790e3
Revises: c77d2d33b2ab
Create Date: 2025-10-24 22:20:14.156995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2197cb1790e3'
down_revision = 'c77d2d33b2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_manual_assignment', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_for_manual_assignment', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.drop_column('flag_for_manual_assignment')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('needs_manual_assignment')

    # ### end Alembic commands ###
