"""Add NotificationRule model

Revision ID: 2a41a342382c
Revises: ac9c66589cc7
Create Date: 2025-11-04 23:02:57.492974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a41a342382c'
down_revision = 'ac9c66589cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('criteria_type', sa.String(length=50), nullable=False),
    sa.Column('criteria_value', sa.Float(), nullable=False),
    sa.Column('notification_method', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_rule')
    # ### end Alembic commands ###
