"""Add current_balance and balance_last_updated to Account

Revision ID: 2d2a1aac8490
Revises: 69e87f866bc1
Create Date: 2025-09-20 13:25:25.024068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2a1aac8490'
down_revision = '69e87f866bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('balance_last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('balance_last_updated')
        batch_op.drop_column('current_balance')

    # ### end Alembic commands ###
