"""Add transaction_id to journal entry

Revision ID: 30955be0b656
Revises: e0b7ad376907
Create Date: 2025-09-01 14:48:59.513703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30955be0b656'
down_revision = 'e0b7ad376907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_journal_entries_transaction_id', 'transaction', ['transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_journal_entries_transaction_id', type_='foreignkey')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
