"""implement double-entry bookkeeping

Revision ID: 39f971fb1995
Revises: 04f32eee6b09
Create Date: 2025-08-17 20:47:55.444838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f971fb1995'
down_revision = '04f32eee6b09'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('DELETE FROM journal_entries')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debit_account_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('credit_account_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_journal_entries_credit_account_id', 'account', ['credit_account_id'], ['id'])
        batch_op.create_foreign_key('fk_journal_entries_debit_account_id', 'account', ['debit_account_id'], ['id'])
        batch_op.drop_column('account_id')
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('account_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])
        batch_op.drop_column('credit_account_id')
        batch_op.drop_column('debit_account_id')

    # ### end Alembic commands ###
