"""Add cursor to PlaidItem

Revision ID: 3ce15c8b19c0
Revises: 2d2a1aac8490
Create Date: 2025-09-22 10:58:36.599519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce15c8b19c0'
down_revision = '2d2a1aac8490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cursor', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_column('cursor')

    # ### end Alembic commands ###
