"""add parent_id to account for sub-accounts

Revision ID: 44ba322e0557
Revises: 02d594cf35ae
Create Date: 2025-08-23 22:54:36.858532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ba322e0557'
down_revision = '02d594cf35ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_account_parent_id', 'account', ['parent_id'], ['id'])

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('business_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('business_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('fk_account_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
