"""Add debit and credit accounts to category rule

Revision ID: 4a5494f717f8
Revises: 0f2c1801113a
Create Date: 2025-08-31 19:24:02.166778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5494f717f8'
down_revision = '0f2c1801113a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debit_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credit_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_category_rule_credit_account_id', 'account', ['credit_account_id'], ['id'])
        batch_op.create_foreign_key('fk_category_rule_debit_account_id', 'account', ['debit_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_rule', schema=None) as batch_op:
        batch_op.drop_constraint('fk_category_rule_credit_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_category_rule_debit_account_id', type_='foreignkey')
        batch_op.drop_column('credit_account_id')
        batch_op.drop_column('debit_account_id')

    # ### end Alembic commands ###
