"""Add keywords column to Budget model

Revision ID: 52ad1cfd0b93
Revises: 2a41a342382c
Create Date: 2025-11-05 13:38:19.394151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ad1cfd0b93'
down_revision = '2a41a342382c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword')
    op.drop_table('budget_keywords')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('keywords')


    op.create_table('budget_keywords',
    sa.Column('budget_id', sa.INTEGER(), nullable=False),
    sa.Column('keyword_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('budget_id', 'keyword_id')
    )
    op.create_table('keyword',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
