"""Add delete_transaction to transaction_rule

Revision ID: 558d86863a1c
Revises: 30955be0b656
Create Date: 2025-09-01 15:23:12.922969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision = '558d86863a1c'
down_revision = '30955be0b656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('transaction_rule')]

    if 'delete_transaction' not in columns:
        with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
            batch_op.add_column(sa.Column('delete_transaction', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.drop_column('delete_transaction')

    # ### end Alembic commands ###
