"""Add cascade delete to plaid items and accounts

Revision ID: 5f53affc919f
Revises: f649e5c84cc6
Create Date: 2025-11-11 15:07:04.202997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f53affc919f'
down_revision = 'f649e5c84cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # with op.batch_alter_table('audit_trail', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    # with op.batch_alter_table('transaction', schema=None) as batch_op:
    #     batch_op.alter_column('needs_manual_assignment',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text("'0'"))

    # with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
    #     batch_op.alter_column('is_automatic',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text("'0'"))
    #     batch_op.alter_column('delete_transaction',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text("'0'"))
    #     batch_op.alter_column('flag_for_manual_assignment',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
    #     batch_op.alter_column('flag_for_manual_assignment',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text("'0'"))
    #     batch_op.alter_column('delete_transaction',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text("'0'"))
    #     batch_op.alter_column('is_automatic',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text("'0'"))

    # with op.batch_alter_table('transaction', schema=None) as batch_op:
    #     batch_op.alter_column('needs_manual_assignment',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text("'0'"))

    # with op.batch_alter_table('audit_trail', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'client', ['user_id'], ['id'])

    # ### end Alembic commands ###
