"""Add institution_name to PlaidItem

Revision ID: 5f6feaa6cb4d
Revises: 5a7e5f143970
Create Date: 2025-09-17 12:17:41.749007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6feaa6cb4d'
down_revision = '5a7e5f143970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_column('institution_name')

    # ### end Alembic commands ###
