"""add financial_period table

Revision ID: 675be0e1338f
Revises: 90c528e6c639
Create Date: 2025-08-24 00:44:13.231526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675be0e1338f'
down_revision = '90c528e6c639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_period')
    # ### end Alembic commands ###
