"""add is_miscellaneous to budget model

Revision ID: 68791837635f
Revises: 52ad1cfd0b93
Create Date: 2025-11-06 09:32:56.538799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68791837635f'
down_revision = '52ad1cfd0b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_miscellaneous', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('is_miscellaneous')

    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client', ['user_id'], ['id'])

    # ### end Alembic commands ###
