"""Add institution_id to PlaidItem

Revision ID: 69e87f866bc1
Revises: a76481a19e79
Create Date: 2025-09-18 10:26:03.111835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e87f866bc1'
down_revision = 'a76481a19e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_column('institution_id')

    # ### end Alembic commands ###
