"""Add source account to transactions and rules

Revision ID: 71dfc3bd5ec4
Revises: 558d86863a1c
Create Date: 2025-09-01 23:40:35.688326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71dfc3bd5ec4'
down_revision = '558d86863a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_source_account', 'account', ['source_account_id'], ['id'])

    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_rule_source_account', 'account', ['source_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_rule_source_account', type_='foreignkey')
        batch_op.drop_column('source_account_id')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_source_account', type_='foreignkey')
        batch_op.drop_column('source_account_id')

    # ### end Alembic commands ###
