"""add debit and credit accounts to rule

Revision ID: 723f7281ab8f
Revises: 44ba322e0557
Create Date: 2025-08-23 23:55:15.956526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723f7281ab8f'
down_revision = '44ba322e0557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debit_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credit_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_rule_credit_account_id', 'account', ['credit_account_id'], ['id'])
        batch_op.create_foreign_key('fk_rule_debit_account_id', 'account', ['debit_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rule_debit_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_rule_credit_account_id', type_='foreignkey')
        batch_op.drop_column('credit_account_id')
        batch_op.drop_column('debit_account_id')

    # ### end Alembic commands ###
