"""Change date columns to Date type

Revision ID: 72825e48a3d0
Revises: 33fbad5fa9d9
Create Date: 2025-09-07 23:50:33.092127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72825e48a3d0'
down_revision = '33fbad5fa9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('depreciation', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('financial_period', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('fixed_asset', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('reversal_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('reconciliation', schema=None) as batch_op:
        batch_op.alter_column('statement_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('recurring_transaction', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('recurring_transaction', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('reconciliation', schema=None) as batch_op:
        batch_op.alter_column('statement_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.alter_column('reversal_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('fixed_asset', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('financial_period', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('depreciation', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
