"""Change category_condition to Text in TransactionRule

Revision ID: 732daf90ba9a
Revises: 71dfc3bd5ec4
Create Date: 2025-09-02 13:49:51.101152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732daf90ba9a'
down_revision = '71dfc3bd5ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.alter_column('category_condition',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.alter_column('category_condition',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
