"""Add FixedAsset and Depreciation models

Revision ID: 749eb3e6c0f6
Revises: 13e2163016ca
Create Date: 2025-08-17 23:28:42.112842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749eb3e6c0f6'
down_revision = '13e2163016ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('purchase_date', sa.String(length=10), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('useful_life', sa.Integer(), nullable=False),
    sa.Column('salvage_value', sa.Float(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depreciation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fixed_asset_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['fixed_asset_id'], ['fixed_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depreciation')
    op.drop_table('fixed_asset')
    # ### end Alembic commands ###
