"""add account_id to rule

Revision ID: 800974ac635f
Revises: 81370425be3e
Create Date: 2025-08-15 17:18:02.761533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800974ac635f'
down_revision = '81370425be3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_rule_account_id', 'account', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rule_account_id', type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
