"""Add initial_sync_complete to PlaidItem

Revision ID: 85c1b9807cc4
Revises: 5f53affc919f
Create Date: 2025-11-12 22:28:27.220752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c1b9807cc4'
down_revision = '5f53affc919f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_sync_complete', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_column('initial_sync_complete')

    # ### end Alembic commands ###
