"""Add initial_sync_complete to PlaidItem

Revision ID: 85c1b9807cc4
Revises: 5f53affc919f
Create Date: 2025-11-12 22:28:27.220752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c1b9807cc4'
down_revision = '5f53affc919f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_sync_complete', sa.Boolean(), nullable=False))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('needs_manual_assignment',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.alter_column('is_automatic',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('delete_transaction',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('flag_for_manual_assignment',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.alter_column('flag_for_manual_assignment',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('delete_transaction',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_automatic',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('needs_manual_assignment',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_column('initial_sync_complete')

    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client', ['user_id'], ['id'])

    # ### end Alembic commands ###
