"""add category_rule table

Revision ID: 90c528e6c639
Revises: 723f7281ab8f
Create Date: 2025-08-24 00:22:54.034288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c528e6c639'
down_revision = '723f7281ab8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('keyword', sa.String(length=100), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_rule')
    # ### end Alembic commands ###
