"""Change budget to be category-based

Revision ID: 9211f3697ed4
Revises: c693a607bd44
Create Date: 2025-09-08 12:43:22.947803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9211f3697ed4'
down_revision = 'c693a607bd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.drop_column('account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'])
        batch_op.drop_column('category')
    # ### end Alembic commands ###
