"""Change budget to be category-based

Revision ID: 9211f3697ed4
Revises: c693a607bd44
Create Date: 2025-09-08 12:43:22.947803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9211f3697ed4'
down_revision = 'c693a607bd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('category', sa.String(length=100), nullable=False))
    op.drop_constraint('budget_account_id_fkey', 'budget', type_='foreignkey')
    op.drop_column('budget', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('budget_account_id_fkey', 'budget', 'account', ['account_id'], ['id'])
    op.drop_column('budget', 'category')
    # ### end Alembic commands ###
