"""Add plaid_transaction_id to Transaction

Revision ID: 930b35bb04ed
Revises: 3ce15c8b19c0
Create Date: 2025-09-22 11:04:52.131594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930b35bb04ed'
down_revision = '3ce15c8b19c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaid_transaction_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_transaction_plaid_transaction_id', ['plaid_transaction_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('uq_transaction_plaid_transaction_id', type_='unique')
        batch_op.drop_column('plaid_transaction_id')

    # ### end Alembic commands ###
