"""Add is_accrual to JournalEntry

Revision ID: 965dda3c0107
Revises: cdd1c30e41a9
Create Date: 2025-08-17 23:32:47.898118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965dda3c0107'
down_revision = 'cdd1c30e41a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accrual', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('is_accrual')

    # ### end Alembic commands ###
