"""add is_reconciled to reconciliation

Revision ID: 9f7b8cdf0675
Revises: ff1d1bb43ba8
Create Date: 2025-11-04 14:41:26.602305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7b8cdf0675'
down_revision = 'ff1d1bb43ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('category')
    # op.drop_table('budget_categories')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_audit_trail_client_id', 'client', ['client_id'], ['id'])
        batch_op.create_foreign_key('fk_audit_trail_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False, server_default=sa.func.date('now')))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False,
               existing_server_default=sa.text("'Budget'"))
        batch_op.alter_column('period',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        # batch_op.alter_column('keywords',
        #        existing_type=sa.TEXT(),
        #        type_=sa.String(length=255),
        #        existing_nullable=True)
        batch_op.create_foreign_key('fk_budget_category_id', 'account', ['category_id'], ['id'])

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('business_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('contact_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('services_offered',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('client_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('journal_entry_id',
               existing_type=sa.INTEGER(),
               nullable=True)

        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False, server_default=''))
        # batch_op.drop_column('is_closed')

    with op.batch_alter_table('fixed_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('depreciation_method', sa.String(length=50), nullable=False, server_default=''))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('cost')

    with op.batch_alter_table('import_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False, server_default=''))
        batch_op.alter_column('has_header',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('negate_amount',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=False, server_default=sa.func.date('now')))

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('locked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_reversing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('transaction_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('reconciliation_id')

    with op.batch_alter_table('pending_plaid_link', schema=None) as batch_op:
        batch_op.alter_column('link_token',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('purpose',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_pending_plaid_link_link_token'))
        batch_op.create_unique_constraint('uq_pending_plaid_link_link_token', ['link_token'])

    with op.batch_alter_table('plaid_account', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('mask',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('subtype',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('institution_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('cursor',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('sale_price', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('cost')

    with op.batch_alter_table('reconciliation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reconciled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('recurring_transaction', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False,
               server_default='')
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               server_default='')
        batch_op.drop_column('name')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_price', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.drop_column('price')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('plaid_transaction_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False,
               server_default='')
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('rule_modified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('needs_manual_assignment')

    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False,
               server_default='')
        batch_op.alter_column('new_category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_column('new_description')
        batch_op.drop_column('is_automatic')
        batch_op.drop_column('min_amount')
        batch_op.drop_column('category_condition')
        batch_op.drop_column('delete_transaction')
        batch_op.drop_column('max_amount')
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('flag_for_manual_assignment')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('contact_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('contact_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_for_manual_assignment', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True))
        batch_op.add_column(sa.Column('transaction_type', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('max_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('delete_transaction', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('category_condition', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('min_amount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('is_automatic', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('new_description', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('new_category',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('keyword',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_manual_assignment', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.alter_column('rule_modified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('plaid_transaction_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('notes')

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.drop_column('sale_price')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('recurring_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('frequency',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('reconciliation', schema=None) as batch_op:
        batch_op.drop_column('is_reconciled')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.FLOAT(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('sale_price')
        batch_op.drop_column('purchase_price')

    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.alter_column('cursor',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('institution_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('institution_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('access_token',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('item_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('plaid_account', schema=None) as batch_op:
        batch_op.alter_column('subtype',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('mask',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('account_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('pending_plaid_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_pending_plaid_link_link_token'), ['link_token'], unique=1)
        batch_op.alter_column('purpose',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('link_token',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reconciliation_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'reconciliation', ['reconciliation_id'], ['id'])
        batch_op.alter_column('transaction_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('is_reversing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('locked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('purchase_date')

    with op.batch_alter_table('import_template', schema=None) as batch_op:
        batch_op.alter_column('negate_amount',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('has_header',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('fixed_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('depreciation_method')
        batch_op.drop_column('purchase_price')

    with op.batch_alter_table('financial_period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('journal_entry_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('upload_date')
        batch_op.drop_column('filepath')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('client_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('services_offered',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('contact_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('business_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.alter_column('keywords',
        #        existing_type=sa.String(length=255),
        #        type_=sa.TEXT(),
        #        existing_nullable=True)
        batch_op.alter_column('period',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'Budget'"))
        batch_op.drop_column('category_id')
        batch_op.drop_column('end_date')

    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'client', ['user_id'], ['id'])
        batch_op.alter_column('action',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('details')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.create_table('budget_categories',
    sa.Column('budget_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('budget_id', 'category_id')
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
