"""Remove vendor_id from transaction

Revision ID: a2e3e0c7fa50
Revises: 72825e48a3d0
Create Date: 2025-09-08 01:02:57.402426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e3e0c7fa50'
down_revision = '72825e48a3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_vendor', type_='foreignkey')
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_vendor', 'vendor', ['vendor_id'], ['id'])

    # ### end Alembic commands ###
