"""Add PendingPlaidLink table

Revision ID: a40461f4f18f
Revises: d01c10f230c1
Create Date: 2025-09-26 10:03:16.161695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40461f4f18f'
down_revision = 'd01c10f230c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_plaid_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_token', sa.String(length=256), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_plaid_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_plaid_link_link_token'), ['link_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_plaid_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_plaid_link_link_token'))

    op.drop_table('pending_plaid_link')
    # ### end Alembic commands ###
