"""Create PlaidAccount model

Revision ID: a76481a19e79
Revises: e53bfced88b8
Create Date: 2025-09-17 12:55:37.987934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76481a19e79'
down_revision = 'e53bfced88b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaid_item_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mask', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('subtype', sa.String(length=50), nullable=False),
    sa.Column('local_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['local_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_plaid_item_account_id'), type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_plaid_item_account_id'), 'account', ['account_id'], ['id'])

    op.drop_table('plaid_account')
    # ### end Alembic commands ###
