"""add negate_amount to import_template

Revision ID: ab5ef2d7920a
Revises: b5a1d53c03dd
Create Date: 2025-08-15 23:29:56.625292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5ef2d7920a'
down_revision = 'b5a1d53c03dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('negate_amount', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_template', schema=None) as batch_op:
        batch_op.drop_column('negate_amount')

    # ### end Alembic commands ###
