"""add vendor to transaction

Revision ID: ad3bf76bf4cc
Revises: ce665dcc6d45
Create Date: 2025-09-07 22:44:18.725030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3bf76bf4cc'
down_revision = 'ce665dcc6d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_vendor', 'vendor', ['vendor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_vendor', type_='foreignkey')
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###
