"""add keywords to budget model

Revision ID: af3f3546b8bb
Revises: f7cf5fd4be91
Create Date: 2025-10-30 15:22:42.140286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3f3546b8bb'
down_revision = 'f7cf5fd4be91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_budget_parent_id', 'budget', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint('fk_budget_parent_id', type_='foreignkey')
        batch_op.drop_column('keywords')



    # ### end Alembic commands ###
