"""add name to budget model

Revision ID: b54f9f8868f1
Revises: ed2b80dbabfd
Create Date: 2025-10-30 09:37:36.879615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54f9f8868f1'
down_revision = 'ed2b80dbabfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False, server_default='Budget'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('name')



    # ### end Alembic commands ###
