"""link import templates to accounts

Revision ID: b5a1d53c03dd
Revises: 0f71d38505d8
Create Date: 2025-08-15 23:10:00.701484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a1d53c03dd'
down_revision = '0f71d38505d8'
branch_labels = None
depends_on = None


def upgrade():
    # Clear existing templates since we are changing the structure
    op.execute('DELETE FROM import_template')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_import_template_account_id', ['account_id'])
        batch_op.create_foreign_key('fk_import_template_account_id', 'account', ['account_id'], ['id'])
        batch_op.drop_column('client_id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
