"""Change budget category to string

Revision ID: b9be6e2c60ce
Revises: 9f7b8cdf0675
Create Date: 2025-11-04 15:39:27.544462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9be6e2c60ce'
down_revision = '9f7b8cdf0675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=120), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_budget_category_id'), type_='foreignkey')
        # batch_op.drop_column('keywords')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('financial_period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_column('is_closed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), server_default=sa.text("('')"), nullable=False))

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_budget_category_id'), 'account', ['category_id'], ['id'])
        batch_op.drop_column('category')



    # ### end Alembic commands ###
