"""Fix AuditTrail model foreign key

Revision ID: c77d2d33b2ab
Revises: 308be7a44f30
Create Date: 2025-10-10 13:15:59.969920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77d2d33b2ab'
down_revision = '308be7a44f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_audit_trail_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_trail_user_id', type_='foreignkey')

    # ### end Alembic commands ###
