"""Add rule_modified to Transaction

Revision ID: dad75be58ee8
Revises: 0ae6d8e0947a
Create Date: 2025-08-25 08:46:40.796026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad75be58ee8'
down_revision = '0ae6d8e0947a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_modified', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('rule_modified')

    # ### end Alembic commands ###
