"""Add unique constraint to client business name

Revision ID: dd078d4f033e
Revises: 5f53affc919f
Create Date: 2025-11-16 20:03:14.292578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd078d4f033e'
down_revision = '5f53affc919f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_client_business_name', ['business_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('uq_client_business_name', type_='unique')
    # ### end Alembic commands ###
