"""Add is_automatic to transaction rule

Revision ID: e0b7ad376907
Revises: ea7034a37a08
Create Date: 2025-09-01 02:17:20.276616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b7ad376907'
down_revision = 'ea7034a37a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_automatic', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.drop_column('is_automatic')

    # ### end Alembic commands ###
