"""Add account_id to PlaidItem

Revision ID: e53bfced88b8
Revises: 5f6feaa6cb4d
Create Date: 2025-09-17 12:35:31.666042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53bfced88b8'
down_revision = '5f6feaa6cb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_plaid_item_account_id', 'account', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plaid_item_account_id', type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
