"""Add purpose to PendingPlaidLink

Revision ID: e65985acdb85
Revises: 058b84186064
Create Date: 2025-10-07 11:06:37.230075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65985acdb85'
down_revision = '058b84186064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_plaid_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_plaid_link', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
