"""Add debit and credit account actions to transaction rules

Revision ID: ea7034a37a08
Revises: 44cbfc3ebf1a
Create Date: 2025-09-01 02:03:10.245365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7034a37a08'
down_revision = '44cbfc3ebf1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_debit_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('new_credit_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_rule_new_credit_account_id', 'account', ['new_credit_account_id'], ['id'])
        batch_op.create_foreign_key('fk_transaction_rule_new_debit_account_id', 'account', ['new_debit_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_rule_new_debit_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_transaction_rule_new_credit_account_id', type_='foreignkey')
        batch_op.drop_column('new_credit_account_id')
        batch_op.drop_column('new_debit_account_id')

    # ### end Alembic commands ###
