"""remove category rule table

Revision ID: ed2b80dbabfd
Revises: 2197cb1790e3
Create Date: 2025-10-29 15:27:05.105900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2b80dbabfd'
down_revision = '2197cb1790e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_rule')
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_trail_user_id', type_='foreignkey')

    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.alter_column('flag_for_manual_assignment',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.alter_column('flag_for_manual_assignment',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client', ['user_id'], ['id'])

    op.create_table('category_rule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('keyword', sa.VARCHAR(length=100), nullable=True),
    sa.Column('condition', sa.VARCHAR(length=20), nullable=True),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('debit_account_id', sa.INTEGER(), nullable=True),
    sa.Column('credit_account_id', sa.INTEGER(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['credit_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['debit_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
