"""add fields to transaction rule

Revision ID: f649e5c84cc6
Revises: 68791837635f
Create Date: 2025-11-10 21:59:21.454103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f649e5c84cc6'
down_revision = '68791837635f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('audit_trail', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_manual_assignment', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_condition', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('min_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('new_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_automatic', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('delete_transaction', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('flag_for_manual_assignment', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.drop_column('flag_for_manual_assignment')
        batch_op.drop_column('delete_transaction')
        batch_op.drop_column('is_automatic')
        batch_op.drop_column('new_description')
        batch_op.drop_column('max_amount')
        batch_op.drop_column('min_amount')
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('category_condition')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('needs_manual_assignment')

    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client', ['user_id'], ['id'])

    # ### end Alembic commands ###
