"""add parent_id to budget model

Revision ID: f7cf5fd4be91
Revises: b54f9f8868f1
Create Date: 2025-10-30 14:56:23.692342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cf5fd4be91'
down_revision = 'b54f9f8868f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_budget_parent_id', 'budget', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint('fk_budget_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')



    # ### end Alembic commands ###
